"""Starter snippet library — loaded only when the data file is missing or empty.

~25 snippets per category, covering the commands most developers reach for
day to day, regardless of stack.
"""
import re

SEED_CATEGORIES = [
    {
        "id": "git", "label": "Git", "icon": "⎇",
        "snippets": [
            ("New branch from current", "git checkout -b {{branch_name}}", "Create and switch to a new branch"),
            ("Switch branch", "git checkout {{branch_name}}", "Switch to an existing branch"),
            ("Stash changes with message", 'git stash push -m "{{message}}"', "Shelve uncommitted work"),
            ("Apply latest stash", "git stash pop", "Re-apply and drop the most recent stash"),
            ("List stashes", "git stash list", "See all shelved changes"),
            ("Pretty log graph", "git log --oneline --graph --decorate --all -n {{count}}", "Compact visual commit history"),
            ("Undo last commit, keep changes", "git reset --soft HEAD~1", "Uncommit but keep changes staged"),
            ("Undo last commit, discard changes", "git reset --hard HEAD~1", "Fully discard the last commit"),
            ("Diff staged changes", "git diff --staged", "Show what's about to be committed"),
            ("Diff two branches", "git diff {{branch_a}} {{branch_b}}", "Compare two branches"),
            ("Delete local branch", "git branch -D {{branch_name}}", "Force-delete a local branch"),
            ("List all branches", "git branch -a", "Local and remote branches"),
            ("Fetch and prune", "git fetch --all --prune", "Sync remotes and remove stale refs"),
            ("Pull with rebase", "git pull --rebase origin {{branch_name}}", "Avoid merge commits when pulling"),
            ("Push branch to origin", "git push origin {{branch_name}}", "Push a branch upstream"),
            ("Force push safely", "git push --force-with-lease", "Force push without clobbering others' work"),
            ("Merge a branch", "git merge {{branch_name}}", "Merge a branch into the current one"),
            ("Interactive rebase", "git rebase -i HEAD~{{count}}", "Squash/reorder/edit recent commits"),
            ("Cherry-pick a commit", "git cherry-pick {{commit_hash}}", "Apply a specific commit onto current branch"),
            ("Create a tag", "git tag {{tag_name}}", "Tag the current commit"),
            ("Show remotes", "git remote -v", "List configured remotes"),
            ("Clone a repo", "git clone {{repo_url}}", "Clone a repository"),
            ("File history", "git log -p -- {{file}}", "Full diff history of a single file"),
            ("Blame a file", "git blame {{file}}", "See who changed each line"),
            ("Clean untracked files", "git clean -fd", "Remove untracked files and directories"),
            ("Amend last commit", "git commit --amend --no-edit", "Add staged changes to the last commit"),
            ("Revert a commit", "git revert {{commit_hash}}", "Create a new commit undoing a past one"),
            ("Check status", "git status", "Show changed, staged, and untracked files"),
            ("Stage all changes", "git add -A", "Stage everything, including deletions"),
            ("Commit staged changes", 'git commit -m "{{message}}"', "Create a commit"),
            ("Initialize a repo", "git init", "Initialize a new git repository"),
            ("Diff unstaged changes", "git diff", "Show changes not yet staged"),
            ("Show a commit", "git show {{commit_hash}}", "Show the diff introduced by a commit"),
            ("Unstage a file", "git reset {{file}}", "Remove a file from the staging area without discarding changes"),
            ("Apply a stash without dropping it", "git stash apply", "Re-apply a stash but keep it in the list"),
        ],
    },
    {
        "id": "docker", "label": "Docker", "icon": "🐳",
        "snippets": [
            ("Build image with tag", "docker build -t {{image_name}}:{{tag}} .", "Build from Dockerfile in current dir"),
            ("Build without cache", "docker build --no-cache -t {{image_name}} .", "Force a clean rebuild"),
            ("Run container interactively", "docker run -it --rm {{image_name}} /bin/sh", "Run and drop into a shell"),
            ("Run container with port mapping", "docker run -d -p {{host_port}}:{{container_port}} --name {{container_name}} {{image_name}}", "Run detached with a mapped port"),
            ("Exec into running container", "docker exec -it {{container_name}} /bin/sh", "Open a shell in a running container"),
            ("Follow container logs", "docker logs -f {{container_name}}", "Stream logs live"),
            ("List running containers", "docker ps", "Show active containers"),
            ("List all containers", "docker ps -a", "Include stopped containers"),
            ("Stop a container", "docker stop {{container_name}}", "Gracefully stop a container"),
            ("Start a container", "docker start {{container_name}}", "Start a stopped container"),
            ("Restart a container", "docker restart {{container_name}}", "Restart a container"),
            ("Remove a container", "docker rm {{container_name}}", "Delete a stopped container"),
            ("Stop and remove all containers", "docker rm -f $(docker ps -aq)", "Clean slate — force removes everything"),
            ("Remove an image", "docker rmi {{image_name}}", "Delete a local image"),
            ("List images", "docker images", "Show all local images"),
            ("Prune unused images/volumes", "docker system prune -af --volumes", "Reclaim disk space"),
            ("List volumes", "docker volume ls", "Show all volumes"),
            ("List networks", "docker network ls", "Show all networks"),
            ("Copy file from container", "docker cp {{container_name}}:{{src_path}} {{dest_path}}", "Copy a file out of a container"),
            ("Inspect a container", "docker inspect {{container_name}}", "Full JSON metadata for a container"),
            ("Compose up", "docker-compose up -d", "Start all services in the background"),
            ("Compose down", "docker-compose down", "Stop and remove compose services"),
            ("Compose logs for a service", "docker-compose logs -f {{service_name}}", "Stream logs for one service"),
            ("Tag an image for a registry", "docker tag {{image_name}} {{registry}}/{{image_name}}:{{tag}}", "Prepare an image for pushing"),
            ("Push image to registry", "docker push {{registry}}/{{image_name}}:{{tag}}", "Upload an image"),
            ("Pull an image", "docker pull {{image_name}}:{{tag}}", "Download an image"),
            ("Live resource usage", "docker stats", "CPU/memory usage per container"),
            ("Build with a specific Dockerfile", "docker build -f {{dockerfile}} -t {{image_name}} .", "Use a non-default Dockerfile path"),
            ("Create a network", "docker network create {{network_name}}", "Create a custom bridge network"),
            ("Remove a volume", "docker volume rm {{volume_name}}", "Delete a volume"),
            ("Rebuild compose services", "docker-compose build", "Rebuild images defined in compose"),
            ("Restart compose services", "docker-compose restart", "Restart all services"),
            ("Save image to a tar file", "docker save -o {{file}}.tar {{image_name}}", "Export an image for offline transfer"),
        ],
    },
    {
        "id": "kubernetes", "label": "Kubernetes", "icon": "⎈",
        "snippets": [
            ("Get pods in namespace", "kubectl get pods -n {{namespace}}", "List all pods in a namespace"),
            ("Get pods with node info", "kubectl get pods -o wide -n {{namespace}}", "Include node placement"),
            ("Describe pod", "kubectl describe pod {{pod}} -n {{namespace}}", "Detailed pod info and events"),
            ("Follow pod logs", "kubectl logs -f {{pod}} -n {{namespace}}", "Stream logs from a pod"),
            ("Logs from previous container", "kubectl logs {{pod}} -n {{namespace}} --previous", "Debug a crashed container"),
            ("Exec into pod", "kubectl exec -it {{pod}} -n {{namespace}} -- /bin/sh", "Open a shell inside a pod"),
            ("Port-forward to pod", "kubectl port-forward {{pod}} {{local_port}}:{{remote_port}} -n {{namespace}}", "Forward a local port to the pod"),
            ("Restart a deployment", "kubectl rollout restart deployment/{{deployment}} -n {{namespace}}", "Roll all pods of a deployment"),
            ("Check rollout status", "kubectl rollout status deployment/{{deployment}} -n {{namespace}}", "Watch a rollout progress"),
            ("Undo a rollout", "kubectl rollout undo deployment/{{deployment}} -n {{namespace}}", "Roll back to the previous revision"),
            ("Get all resources", "kubectl get all -n {{namespace}}", "Overview of everything in a namespace"),
            ("Get services", "kubectl get svc -n {{namespace}}", "List services in a namespace"),
            ("Get deployments", "kubectl get deployments -n {{namespace}}", "List deployments in a namespace"),
            ("Get nodes", "kubectl get nodes", "List cluster nodes"),
            ("Describe a node", "kubectl describe node {{node}}", "Detailed node info"),
            ("Apply a manifest", "kubectl apply -f {{file}}", "Create/update resources from a file"),
            ("Delete from a manifest", "kubectl delete -f {{file}}", "Delete resources defined in a file"),
            ("Delete a pod", "kubectl delete pod {{pod}} -n {{namespace}}", "Force a pod to be recreated"),
            ("Scale a deployment", "kubectl scale deployment/{{deployment}} --replicas={{count}} -n {{namespace}}", "Change replica count"),
            ("Recent events, newest last", "kubectl get events -n {{namespace}} --sort-by=.lastTimestamp", "Debug cluster-level issues"),
            ("Pod resource usage", "kubectl top pods -n {{namespace}}", "Live CPU/memory per pod"),
            ("List contexts", "kubectl config get-contexts", "Show available cluster contexts"),
            ("Switch context", "kubectl config use-context {{context_name}}", "Change active cluster"),
            ("Read a configmap", "kubectl get configmap {{name}} -n {{namespace}} -o yaml", "Dump a configmap as YAML"),
            ("Read a secret", "kubectl get secret {{name}} -n {{namespace}} -o yaml", "Dump a secret as YAML (base64)"),
            ("Edit a deployment live", "kubectl edit deployment/{{deployment}} -n {{namespace}}", "Open a deployment in your editor"),
            ("Copy file from pod", "kubectl cp {{namespace}}/{{pod}}:{{src_path}} {{dest_path}}", "Copy a file out of a pod"),
            ("Create a namespace", "kubectl create namespace {{namespace}}", "Create a new namespace"),
            ("List namespaces", "kubectl get namespaces", "List all namespaces"),
            ("Pods across all namespaces", "kubectl get pods -A", "List pods in every namespace"),
            ("Node resource usage", "kubectl top nodes", "Live CPU/memory per node"),
            ("Update deployment image", "kubectl set image deployment/{{deployment}} {{container}}={{image}} -n {{namespace}}", "Roll a new image without editing YAML"),
            ("List ingresses", "kubectl get ingress -n {{namespace}}", "List ingress resources in a namespace"),
            ("List persistent volume claims", "kubectl get pvc -n {{namespace}}", "List PVCs in a namespace"),
            ("Describe a deployment", "kubectl describe deployment {{deployment}} -n {{namespace}}", "Detailed deployment info and events"),
        ],
    },
    {
        "id": "python", "label": "Python", "icon": "🐍",
        "snippets": [
            ("Create virtualenv", "python3 -m venv {{env_name}}", "Create a new virtual environment"),
            ("Activate virtualenv", "source {{env_name}}/bin/activate", "Activate on macOS/Linux"),
            ("Deactivate virtualenv", "deactivate", "Exit the active virtual environment"),
            ("Install requirements", "pip install -r requirements.txt", "Install project dependencies"),
            ("Install a package", "pip install {{package_name}}", "Add a single dependency"),
            ("Uninstall a package", "pip uninstall {{package_name}}", "Remove a dependency"),
            ("Freeze dependencies", "pip freeze > requirements.txt", "Snapshot installed packages"),
            ("List outdated packages", "pip list --outdated", "See what needs updating"),
            ("Upgrade a package", "pip install --upgrade {{package_name}}", "Update to the latest version"),
            ("Run tests", "pytest {{path}} -v", "Verbose test run"),
            ("Run matching tests", 'pytest -k "{{pattern}}"', "Run only tests matching a name pattern"),
            ("Run tests with coverage", "pytest --cov={{package}} {{path}}", "Measure test coverage"),
            ("Format with black", "black {{path}}", "Auto-format code"),
            ("Lint with ruff, auto-fix", "ruff check {{path}} --fix", "Lint and auto-fix"),
            ("Lint with flake8", "flake8 {{path}}", "Style and error checking"),
            ("Type check with mypy", "mypy {{path}}", "Static type checking"),
            ("Serve current dir over HTTP", "python3 -m http.server {{port}}", "Quick local file server"),
            ("Pretty-print JSON file", "python3 -m json.tool {{file}}", "Validate and format JSON"),
            ("Print Python version", "python3 -c \"import sys; print(sys.version)\"", "Check interpreter version"),
            ("Poetry install", "poetry install", "Install dependencies from pyproject.toml"),
            ("Poetry add a package", "poetry add {{package_name}}", "Add a dependency via Poetry"),
            ("Poetry run a command", "poetry run {{command}}", "Run inside the Poetry-managed environment"),
            ("Build sdist and wheel", "python3 setup.py sdist bdist_wheel", "Build distributable packages"),
            ("Upgrade pip itself", "python3 -m pip install --upgrade pip", "Update the packaging tool"),
            ("Sort imports", "isort {{path}}", "Auto-sort and group imports"),
            ("Debug a script", "python3 -m pdb {{script}}", "Step through with the interactive debugger"),
            ("Recreate a virtualenv from scratch", "python3 -m venv {{env_name}} --clear", "Wipe and rebuild the environment"),
            ("Run a script", "python3 {{script}}", "Execute a Python file"),
            ("Install in editable mode", "pip install -e .", "Install the current project for local development"),
            ("Show package info", "pip show {{package_name}}", "Version, location, and dependencies of a package"),
            ("List installed packages", "pip list", "Show everything installed in the environment"),
            ("Print interpreter version", "python3 --version", "Quick version check"),
        ],
    },
    {
        "id": "javascript", "label": "JavaScript / Node", "icon": "⬡",
        "snippets": [
            ("Install dependencies", "npm install", "Install from package.json"),
            ("Add a package", "npm install {{package_name}}", "Add a dependency"),
            ("Add a dev dependency", "npm install -D {{package_name}}", "Add a dev-only dependency"),
            ("Install a package globally", "npm install -g {{package_name}}", "Make a CLI tool available everywhere"),
            ("Remove a package", "npm uninstall {{package_name}}", "Remove a dependency"),
            ("Run a script", "npm run {{script_name}}", "Run any package.json script"),
            ("Run dev script", "npm run dev", "Start the dev server"),
            ("Run build script", "npm run build", "Produce a production build"),
            ("Run tests", "npm test", "Run the test suite"),
            ("List outdated packages", "npm outdated", "See what needs updating"),
            ("Fix known vulnerabilities", "npm audit fix", "Auto-fix reported vulnerabilities"),
            ("Clean install from lockfile", "npm ci", "Reproducible install for CI"),
            ("List top-level packages", "npm list --depth=0", "Show direct dependencies"),
            ("One-off run without installing", "npx {{package_name}}", "Run a package without a global install"),
            ("Scaffold a React app", "npx create-react-app {{app_name}}", "Bootstrap a new React project"),
            ("Yarn install", "yarn install", "Install from package.json"),
            ("Yarn add a package", "yarn add {{package_name}}", "Add a dependency"),
            ("Yarn add a dev dependency", "yarn add -D {{package_name}}", "Add a dev-only dependency"),
            ("Yarn remove a package", "yarn remove {{package_name}}", "Remove a dependency"),
            ("Yarn run a script", "yarn run {{script_name}}", "Run a package.json script"),
            ("pnpm install", "pnpm install", "Install from package.json"),
            ("pnpm add a package", "pnpm add {{package_name}}", "Add a dependency"),
            ("Run a JS file", "node {{file}}", "Execute a script with Node"),
            ("Run inline JS", 'node -e "{{code}}"', "Evaluate a snippet directly"),
            ("Init a new package.json", "npm init -y", "Scaffold package.json with defaults"),
            ("Bump package version", "npm version {{version_type}}", "patch / minor / major"),
            ("Link a local package", "npm link", "Symlink a package for local development"),
            ("Check Node version", "node --version", "Check installed Node version"),
            ("Clear npm cache", "npm cache clean --force", "Fix corrupted cache issues"),
            ("Yarn build", "yarn build", "Produce a production build with Yarn"),
            ("Yarn test", "yarn test", "Run the test suite with Yarn"),
        ],
    },
    {
        "id": "bash", "label": "Bash / Linux", "icon": "💻",
        "snippets": [
            ("Find files by name", 'find {{path}} -iname "*{{pattern}}*"', "Case-insensitive recursive search"),
            ("Find recently modified files", "find {{path}} -type f -mtime -{{days}}", "Files changed in the last N days"),
            ("Recursive grep for text", 'grep -rn "{{pattern}}" {{path}}', "Search file contents recursively"),
            ("Grep excluding a pattern", 'grep -v "{{pattern}}" {{file}}', "Show lines that don't match"),
            ("Make script executable", "chmod +x {{file}}", "Add execute permission"),
            ("Change file permissions", "chmod {{mode}} {{file}}", "Set exact permission bits"),
            ("Change file owner", "chown {{user}}:{{group}} {{file}}", "Change ownership"),
            ("Find process on a port", "lsof -i :{{port}}", "See what's holding a port"),
            ("Kill process by PID", "kill -9 {{pid}}", "Force-kill a process"),
            ("Find process by name", "ps aux | grep {{process_name}}", "List matching running processes"),
            ("Disk free space", "df -h", "Human-readable disk usage per mount"),
            ("Disk usage by directory", "du -sh {{path}}/* | sort -rh", "Largest directories first"),
            ("Extract a tarball", "tar -xzvf {{file}}.tar.gz", "Unpack a gzipped tarball"),
            ("Create a tarball", "tar -czvf {{archive_name}}.tar.gz {{path}}", "Compress a directory"),
            ("SSH into a host", "ssh {{user}}@{{host}}", "Open a remote shell"),
            ("Copy file to remote host", "scp {{local_file}} {{user}}@{{host}}:{{remote_path}}", "Secure copy over SSH"),
            ("Sync directories", "rsync -avz {{src}} {{dest}}", "Efficient incremental copy"),
            ("Run a command per line of input", "xargs -I{} {{command}} {}", "Feed piped input into a command"),
            ("In-place find and replace", 'sed -i "s/{{old}}/{{new}}/g" {{file}}', "Replace text in a file"),
            ("Print a column of output", "awk '{print ${{column}}}' {{file}}", "Extract a field from each line"),
            ("Follow a growing file", "tail -f {{file}}", "Stream new lines as they're written"),
            ("Show first N lines", "head -n {{lines}} {{file}}", "Preview the start of a file"),
            ("Count lines in a file", "wc -l {{file}}", "Line count"),
            ("Search shell history", "history | grep {{pattern}}", "Find a command you ran before"),
            ("Create a shell alias", 'alias {{name}}="{{command}}"', "Shortcut for a longer command"),
            ("Edit the crontab", "crontab -e", "Edit scheduled jobs"),
            ("Make nested directories", "mkdir -p {{path}}", "Create a directory and any missing parents"),
            ("Copy a directory recursively", "cp -r {{src}} {{dest}}", "Copy a directory and its contents"),
            ("Move or rename", "mv {{src}} {{dest}}", "Move or rename a file or directory"),
            ("Create a symlink", "ln -s {{target}} {{link_name}}", "Create a symbolic link"),
            ("Locate a command", "which {{command}}", "Show which binary a command resolves to"),
            ("Check a service's status", "systemctl status {{service}}", "Show status of a systemd service"),
            ("Restart a service", "systemctl restart {{service}}", "Restart a systemd service"),
            ("Follow a service's logs", "journalctl -u {{service}} -f", "Stream live logs for a systemd service"),
        ],
    },
    {
        "id": "api", "label": "API / cURL", "icon": "🌐",
        "snippets": [
            ("GET with auth header", 'curl -s -H "Authorization: Bearer {{token}}" {{url}}', "Authenticated GET request"),
            ("POST JSON body", "curl -s -X POST {{url}} -H \"Content-Type: application/json\" -d '{{json_body}}'", "Send a JSON payload"),
            ("PUT JSON body", "curl -s -X PUT {{url}} -H \"Content-Type: application/json\" -d '{{json_body}}'", "Replace a resource"),
            ("PATCH JSON body", "curl -s -X PATCH {{url}} -H \"Content-Type: application/json\" -d '{{json_body}}'", "Partially update a resource"),
            ("DELETE request", "curl -s -X DELETE {{url}}", "Delete a resource"),
            ("Download a file", "curl -o {{output_file}} {{url}}", "Save response to a file"),
            ("Verbose request for debugging", "curl -v {{url}}", "Show request/response headers"),
            ("Check response status only", 'curl -s -o /dev/null -w "%{http_code}" {{url}}', "Print just the HTTP status code"),
            ("Pretty-print JSON response", "curl -s {{url}} | jq '.'", "Pipe response through jq"),
            ("HEAD request only", "curl -I {{url}}", "Fetch headers without the body"),
            ("Basic auth", "curl -u {{username}}:{{password}} {{url}}", "Username/password authentication"),
            ("Send a cookie", 'curl --cookie "{{cookie}}" {{url}}', "Include a cookie header"),
            ("Upload a file", 'curl -F "file=@{{file_path}}" {{url}}', "Multipart file upload"),
            ("Measure total request time", 'curl -s -w "\\nTime: %{time_total}s\\n" {{url}}', "Time a request end to end"),
            ("Follow redirects", "curl -L {{url}}", "Follow 3xx redirect chains"),
            ("Skip TLS verification", "curl -k {{url}}", "Ignore invalid/self-signed certs (dev only)"),
            ("Custom DNS resolution", "curl --resolve {{host}}:{{port}}:{{ip}} {{url}}", "Hit a specific IP for a hostname"),
            ("Request through a proxy", "curl -x {{proxy}} {{url}}", "Route the request via a proxy"),
            ("Request JSON explicitly", 'curl -s -H "Accept: application/json" {{url}}', "Ask the server for JSON"),
            ("Preview first N lines of a response", "curl -s {{url}} -o - | head -{{lines}}", "Peek at a large response"),
            ("Force HTTP/2", "curl --http2 {{url}}", "Use HTTP/2 for the request"),
            ("Set a custom user agent", 'curl -A "{{user_agent}}" {{url}}', "Override the default User-Agent"),
            ("URL-encoded form POST", 'curl -s -X POST {{url}} --data-urlencode "{{key}}={{value}}"', "Send classic form-encoded data"),
            ("Timing breakdown", 'curl -s {{url}} -w "%{time_connect} %{time_starttransfer} %{time_total}\\n" -o /dev/null', "Connect/TTFB/total timing"),
            ("Retry on failure", "curl -s --retry {{count}} {{url}}", "Automatically retry a flaky request"),
            ("CORS preflight check", "curl -X OPTIONS {{url}} -I", "Inspect CORS preflight response headers"),
            ("Request compressed response", "curl --compressed {{url}}", "Accept and auto-decompress gzip/deflate"),
        ],
    },
    {
        "id": "aws", "label": "AWS CLI", "icon": "▲",
        "snippets": [
            ("Interactive credentials setup", "aws configure", "Set access key, secret, region, output format"),
            ("List configured profiles/settings", "aws configure list", "Show the active configuration"),
            ("Who am I", "aws sts get-caller-identity", "Show the current account/user/role"),
            ("SSO login", "aws sso login --profile {{profile_name}}", "Authenticate via AWS SSO"),
            ("List S3 buckets", "aws s3 ls", "List all buckets in the account"),
            ("List objects in a bucket", "aws s3 ls s3://{{bucket}}", "List objects under a bucket/prefix"),
            ("Copy a file to S3", "aws s3 cp {{local_path}} s3://{{bucket}}/{{key}}", "Upload a single file"),
            ("Sync a directory to S3", "aws s3 sync {{local_path}} s3://{{bucket}}/{{prefix}}", "Upload only changed files"),
            ("Remove an S3 object", "aws s3 rm s3://{{bucket}}/{{key}}", "Delete a single object"),
            ("Create a bucket", "aws s3 mb s3://{{bucket}}", "Make a new S3 bucket"),
            ("List EC2 instances", "aws ec2 describe-instances", "Show all EC2 instances and their state"),
            ("Start an EC2 instance", "aws ec2 start-instances --instance-ids {{instance_id}}", "Power on an instance"),
            ("Stop an EC2 instance", "aws ec2 stop-instances --instance-ids {{instance_id}}", "Power off an instance"),
            ("List security groups", "aws ec2 describe-security-groups", "Show all security groups"),
            ("List IAM users", "aws iam list-users", "Show all IAM users in the account"),
            ("List IAM roles", "aws iam list-roles", "Show all IAM roles in the account"),
            ("Tail CloudWatch logs", "aws logs tail {{log_group}} --follow", "Stream a log group live"),
            ("Invoke a Lambda function", "aws lambda invoke --function-name {{function_name}} {{output_file}}", "Synchronously invoke and save the response"),
            ("List Lambda functions", "aws lambda list-functions", "Show all Lambda functions"),
            ("Deploy a CloudFormation stack", "aws cloudformation deploy --template-file {{template_file}} --stack-name {{stack_name}}", "Create or update a stack"),
            ("Describe a CloudFormation stack", "aws cloudformation describe-stacks --stack-name {{stack_name}}", "Show stack status and outputs"),
            ("Docker login to ECR", "aws ecr get-login-password --region {{region}} | docker login --username AWS --password-stdin {{registry}}", "Authenticate Docker against an ECR registry"),
            ("List ECS clusters", "aws ecs list-clusters", "Show all ECS clusters"),
            ("List ECS tasks in a cluster", "aws ecs list-tasks --cluster {{cluster_name}}", "Show running tasks"),
            ("List RDS instances", "aws rds describe-db-instances", "Show all RDS database instances"),
            ("Read a Secrets Manager secret", "aws secretsmanager get-secret-value --secret-id {{secret_id}}", "Fetch a secret's current value"),
            ("Update kubeconfig for an EKS cluster", "aws eks update-kubeconfig --name {{cluster_name}} --region {{region}}", "Wire up kubectl for an EKS cluster"),
            ("Assume an IAM role", "aws sts assume-role --role-arn {{role_arn}} --role-session-name {{session_name}}", "Get temporary credentials for a role"),
            ("Start an SSM session", "aws ssm start-session --target {{instance_id}}", "Shell into an instance without SSH or a bastion"),
            ("Scan a DynamoDB table", "aws dynamodb scan --table-name {{table_name}}", "Read all items in a table"),
            ("List SQS queues", "aws sqs list-queues", "Show all SQS queues"),
            ("List load balancers", "aws elbv2 describe-load-balancers", "Show all ALBs/NLBs"),
        ],
    },
    {
        "id": "azure", "label": "Azure CLI", "icon": "◆",
        "snippets": [
            ("Log in", "az login", "Authenticate the CLI interactively"),
            ("Show current account", "az account show", "Display the active subscription/account"),
            ("Switch subscription", "az account set --subscription {{subscription_id}}", "Change the active subscription"),
            ("List resource groups", "az group list", "Show all resource groups"),
            ("Create a resource group", "az group create --name {{resource_group}} --location {{location}}", "Create a new resource group"),
            ("Delete a resource group", "az group delete --name {{resource_group}}", "Delete a resource group and everything in it"),
            ("List VMs", "az vm list", "Show all virtual machines"),
            ("Start a VM", "az vm start --name {{vm_name}} --resource-group {{resource_group}}", "Power on a VM"),
            ("Stop a VM", "az vm stop --name {{vm_name}} --resource-group {{resource_group}}", "Power off (deallocate) a VM"),
            ("Restart a VM", "az vm restart --name {{vm_name}} --resource-group {{resource_group}}", "Restart a VM"),
            ("List storage accounts", "az storage account list", "Show all storage accounts"),
            ("Upload a blob", "az storage blob upload --account-name {{account_name}} --container-name {{container}} --file {{file_path}} --name {{blob_name}}", "Upload a file to blob storage"),
            ("List blobs in a container", "az storage blob list --account-name {{account_name}} --container-name {{container}}", "Show blobs in a container"),
            ("List web apps", "az webapp list", "Show all App Service web apps"),
            ("Restart a web app", "az webapp restart --name {{app_name}} --resource-group {{resource_group}}", "Restart an App Service app"),
            ("Tail web app logs", "az webapp log tail --name {{app_name}} --resource-group {{resource_group}}", "Stream live logs from an App Service app"),
            ("Get AKS credentials", "az aks get-credentials --name {{cluster_name}} --resource-group {{resource_group}}", "Wire up kubectl for an AKS cluster"),
            ("List AKS clusters", "az aks list", "Show all AKS clusters"),
            ("Docker login to ACR", "az acr login --name {{registry_name}}", "Authenticate Docker against an ACR registry"),
            ("Build an image in ACR", "az acr build --registry {{registry_name}} --image {{image_name}}:{{tag}} .", "Build and push without a local Docker daemon"),
            ("Read a Key Vault secret", "az keyvault secret show --vault-name {{vault_name}} --name {{secret_name}}", "Fetch a secret's current value"),
            ("Set a Key Vault secret", "az keyvault secret set --vault-name {{vault_name}} --name {{secret_name}} --value {{value}}", "Create or update a secret"),
            ("List function apps", "az functionapp list", "Show all Azure Function apps"),
            ("Deploy an ARM template", "az deployment group create --resource-group {{resource_group}} --template-file {{template_file}}", "Deploy infrastructure from a template"),
            ("Show signed-in user", "az ad signed-in-user show", "Show the current Azure AD user"),
            ("List role assignments for a principal", "az role assignment list --assignee {{assignee}}", "Show RBAC role assignments"),
            ("List all resources", "az resource list", "Show all resources in the subscription"),
            ("Show a VM's IP addresses", "az vm list-ip-addresses --name {{vm_name}} --resource-group {{resource_group}}", "Show public/private IPs for a VM"),
            ("List SQL databases", "az sql db list --server {{server_name}} --resource-group {{resource_group}}", "Show databases on a SQL server"),
            ("List container instances", "az container list", "Show all Azure Container Instances"),
            ("List Cosmos DB accounts", "az cosmosdb list", "Show all Cosmos DB accounts"),
        ],
    },
]


def build_seed_data() -> dict:
    categories = []
    for cat in SEED_CATEGORIES:
        snippets = []
        for i, (title, command, description) in enumerate(cat["snippets"], start=1):
            params = [{"name": p, "placeholder": ""} for p in re.findall(r"\{\{(\w+)\}\}", command)]
            snippets.append({
                "id": f"{cat['id']}-{i}",
                "title": title,
                "command": command,
                "description": description,
                "params": params,
            })
        categories.append({"id": cat["id"], "label": cat["label"], "icon": cat["icon"], "snippets": snippets})
    return {"categories": categories}
